---
- name: Instalar chocolatey no servidor Windows
  hosts: windows_servers
  gather_facts: false
  vars_files:
    - ~/user_data.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: ttechadmin
    ansible_password: "{{ adm_password }}"
    ansible_port: 5985

  tasks:

    - name: baixaar e instalar Chocolatey
      win_get_url:
        url: https://chocolatey.org/install.ps1
        dest: C:/Temp/install.ps1
      register: download_result
      ignore_errors: yes

    - name: Executar o script de instalação de Chocolatey
      win_shell: powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile -File C:/Temp/install.ps1
      register: install_result
      ignore_errors: yes

    - name: Comprovar instalação do Chocolatey
      win_shell: choco -v
      register: choco_version
      changed_when: false

    - name: Mostrar versão do Chocolatey
      debug:
        var: choco_version.stdout
