---
- name: Cria diretorio Windows
  hosts: windows_servers
  gather_facts: false
  vars_files:
    - ~/user_data.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: ttechadmin
    ansible_password: "{{ adm_password }}"
    ansible_port: 5985

  tasks:
    - name: Verificar se o diretório já existe
      win_stat:
        path: C:\Temp
      register: dir_check

    - name: Criar diretório
      win_file:
        path: C:\Temp
        state: directory
      when: not dir_check.stat.exists

