- name: Update Windows systems
  hosts: windows_servers
  gather_facts: false
  vars_files:
    - ~/user_data.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: ttechadmin
    ansible_password: "{{ adm_password }}"
    ansible_port: 5985

  tasks:

    - name: Verificar se o diretório já existe
      win_stat:
        path: C:\Temp
      register: dir_check

    - name: Criar diretório
      win_file:
        path: C:\Temp
        state: directory
      when: not dir_check.stat.exists

    - name: Verificar se o IIS já está instalado
      win_stat:
        path: C:\inetpub\wwwroot
      register: iis_installed
      changed_when: false

    - name: Instalar o IIS
      win_feature:
        name: Web-Server
        state: present
      when: not iis_installed.stat.exists

    - name: Reiniciar o servidor IIS
      ansible.windows.win_service:
        name: W3SVC
        state: restarted
      when: not iis_installed.stat.exists

    - name: Check for available updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Definition Updates
          - Updates
        state: searched
      register: updates

    - name: Install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Definition Updates
          - Updates
        state: installed
      register: update_install
      when: updates.updates | length > 0

    - name: Verifica se precisa de reboot
      win_reboot:
        reboot_timeout: 3000
      when: update_install.reboot_required
