---
- name: Perform actions on Windows Server
  hosts: windows_servers
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: ttechadmin
    ansible_password: adm2022!!TTECH
    ansible_port: 5985

  tasks:
    - name: Execute a PowerShell command
      win_shell: Get-Process
      register: process_output

    - name: Display process output
      debug:
        var: process_output.stdout_lines
